local wezterm = require("wezterm")
local configuration = wezterm.config_builder()
local ansi_dark = {"#001100", "#007700", "#00BB00", "#007700", "#009900", "#00BB00", "#005500", "#00BB00"}
local brights_dark = {"#007700", "#007700", "#00BB00", "#007700", "#009900", "#00BB00", "#005500", "#00FF00"}
local ansi_light = {"#001100", "#007700", "#00BB00", "#007700", "#009900", "#00BB00", "#005500", "#00BB00"}
local brights_light = {"#007700", "#007700", "#00BB00", "#007700", "#009900", "#00BB00", "#005500", "#00FF00"}
local ansi = ansi_dark
local brights = brights_dark
configuration.automatically_reload_config = true
configuration.colors = {}
configuration.colors.ansi = ansi
configuration.colors.background = ansi[1]
configuration.colors.brights = brights
configuration.colors.compose_cursor = brights[3]
configuration.colors.copy_mode_active_highlight_bg = ansi[1]
configuration.colors.copy_mode_active_highlight_fg = ansi[1]
configuration.colors.copy_mode_inactive_highlight_bg = brights[3]
configuration.colors.copy_mode_inactive_highlight_fg = brights[8]
configuration.colors.cursor_bg = brights[3]
configuration.colors.cursor_fg = brights[1]
configuration.colors.cursor_border = brights[3]
configuration.colors.foreground = ansi[8]
configuration.colors.launcher_label_bg = ansi[1]
configuration.colors.launcher_label_fg = brights[8]
configuration.colors.indexed = {}
configuration.colors.input_selector_label_bg = ansi[1]
configuration.colors.input_selector_label_fg = brights[8]
configuration.colors.quick_select_label_bg = brights[1]
configuration.colors.quick_select_label_fg = brights[8]
configuration.colors.quick_select_match_bg = ansi[5]
configuration.colors.quick_select_match_fg = brights[8]
configuration.colors.scrollbar_thumb = brights[1]
configuration.colors.selection_fg = brights[1]
configuration.colors.selection_bg = brights[4]
configuration.colors.split = ansi[7]
return configuration
